"""Split module for utils/config.py: defaults."""

from __future__ import annotations
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parents[2]


CONFIG_FILENAME = "config.py"


LEGACY_CONFIG_FILENAME = "config.json"


DEFAULT_CONFIG = {
    "prefix": ",",
    "loglevel": "INFO",
    "db": "bot.db",
    "resource": None,
    "host": None,
    "port": 5222,
    "direct_tls": False,
    "restart_notification_file": "/tmp/envsbot_restart_notification.json",
    "command_timeout_seconds": 30,
    "command_slow_log_seconds": 2.0,
    "database_busy_timeout_ms": 5000,
    "database_wal_enabled": False,
    "backup_dir": "data/backups",
    "backup_keep": 15,
    "backup_retention_days": 0,
    "backup_on_start": True,
    "command_rate_limit_enabled": True,
    "command_rate_limit_capacity": 4,
    "command_rate_limit_refill_amount": 1,
    "command_rate_limit_refill_interval_seconds": 0.5,
    "command_rate_limit_deny_window_seconds": 10.0,
    "command_rate_limit_deny_threshold": 6,
    "command_rate_limit_base_block_seconds": 30.0,
    "command_rate_limit_backoff_multiplier": 2.0,
    "command_rate_limit_max_block_seconds": 3600.0,
    "command_rate_limit_notify_cooldown_seconds": 10.0,
    "command_rate_limit_bypass_role": "moderator",
    "http_timeout_seconds": 8,
    "http_user_agent": "Mozilla/5.0 (compatible; envsbot; +https://github.com/envs-net/envsbot)",
    "allow_private_fetch_urls": False,
    "xmpp_query_timeout_seconds": 8,
    "vcard_fetch_timeout_seconds": 10,
    "updatecheck_timeout_seconds": 15,
    "version_check_enabled": False,
    "version_check_interval": 3600,
    "version_check_url": "https://github.com/envs-net/envsbot/releases/latest",
    "room_invites_enabled": True,
    "room_invite_notify_jid": "",
    "room_invite_max_age_days": 30,
    "room_plugin_defaults": {
        "birthday_notify": False,
        "dice": True,
        "ducks": False,
        "help": False,
        "information": True,
        "karma": False,
        "idlerpg": False,
        "pin": True,
        "poll": False,
        "presence": True,
        "reminder": True,
        "sed": True,
        "tell": True,
        "tools": True,
        "urlcheck": True,
        "vcard": True,
        "weather": True,
        "xkcd": False,
        "xmpp": True,
    },
    "urlcheck_wait_seconds": 120,
    "urlcheck_fetch_timeout_seconds": 8,
    "urlcheck_max_redirects": 5,
    "urlcheck_max_read_bytes": 65536,
    "urlcheck_user_agent": "Mozilla/5.0 (compatible; envsbot; +https://github.com/envs-net/envsbot)",
    "rss_global_query_interval": 1200,
    "max_new_feed_entries": 5,
    "rss_max_entries_per_poll": 10,
    "rss_retry_initial_delay": 300,
    "rss_retry_backoff_multiplier": 2.0,
    "rss_max_backoff_time": 3600,
    "rss_broken_error_threshold": 3,
    "rss_similarity_threshold": 0.8,
    "rss_user_agent": "Mozilla/5.0 (compatible; envsbot; +https://github.com/envs-net/envsbot)",
    "rss_fetch_timeout_seconds": 8,
    "rss_max_redirects": 5,
    "rss_max_read_bytes": 1048576,
    "birthday_cache_ttl_seconds": 43200,
    "birthday_initial_scan_delay_seconds": 10,
    "birthday_check_interval_seconds": 3600,
    "sed_regex_timeout": 1.0,
    "sed_max_pattern_length": 256,
    "sed_max_replacement_length": 1000,
    "sed_max_input_length": 5000,
    "sed_max_output_length": 8000,
    "sed_cache_size": 10,
    "poll_max_options": 10,
    "poll_max_question_len": 200,
    "poll_max_option_len": 100,
    "poll_max_history_per_room": 50,
    "poll_default_multi_max_choices": 3,
    "pin_page_size": 10,
    "pin_recent_cache_size": 80,
    "karma_delay_seconds": 60,
    "tell_delivery_delay_seconds": 5,
    "xkcd_check_interval": 3600,
    "xkcd_index_start_delay_seconds": 30,
    "xkcd_index_request_delay_seconds": 0.15,
    "xkcd_http_timeout": 10,
    "reminder_default_timezone": "UTC",
}


REQUIRED_CONFIG_KEYS = {
    "jid": str,
    "password": str,
    "owner": str,
    "nick": str,
}


OPTIONAL_CONFIG_TYPES = {
    "prefix": str,
    "loglevel": str,
    "db": str,
    "resource": str,
    "restart_notification_file": str,
    "command_timeout_seconds": (int, float),
    "command_slow_log_seconds": (int, float),
    "database_busy_timeout_ms": int,
    "database_wal_enabled": bool,
    "backup_dir": str,
    "backup_keep": int,
    "backup_retention_days": int,
    "backup_on_start": bool,
    "command_rate_limit_enabled": bool,
    "command_rate_limit_capacity": int,
    "command_rate_limit_refill_amount": int,
    "command_rate_limit_refill_interval_seconds": (int, float),
    "command_rate_limit_deny_window_seconds": (int, float),
    "command_rate_limit_deny_threshold": int,
    "command_rate_limit_base_block_seconds": (int, float),
    "command_rate_limit_backoff_multiplier": (int, float),
    "command_rate_limit_max_block_seconds": (int, float),
    "command_rate_limit_notify_cooldown_seconds": (int, float),
    "command_rate_limit_bypass_role": str,
    "stop_cmd": list,
    "admins": list,
    "avatar": str,
    "avatar_type": str,
    "timezone": str,
    "host": str,
    "port": int,
    "direct_tls": bool,
    "http_timeout_seconds": (int, float),
    "http_user_agent": str,
    "allow_private_fetch_urls": bool,
    "xmpp_query_timeout_seconds": (int, float),
    "vcard_fetch_timeout_seconds": (int, float),
    "updatecheck_timeout_seconds": (int, float),
    "rss_global_query_interval": int,
    "max_new_feed_entries": int,
    "rss_max_entries_per_poll": int,
    "rss_retry_initial_delay": int,
    "rss_retry_backoff_multiplier": (int, float),
    "rss_max_backoff_time": int,
    "rss_broken_error_threshold": int,
    "rss_similarity_threshold": (int, float),
    "rss_user_agent": str,
    "rss_fetch_timeout_seconds": (int, float),
    "rss_max_redirects": int,
    "rss_max_read_bytes": int,
    "urlcheck_wait_seconds": int,
    "urlcheck_fetch_timeout_seconds": (int, float),
    "urlcheck_max_redirects": int,
    "urlcheck_max_read_bytes": int,
    "urlcheck_user_agent": str,
    "birthday_cache_ttl_seconds": int,
    "birthday_initial_scan_delay_seconds": int,
    "birthday_check_interval_seconds": int,
    "sed_regex_timeout": (int, float),
    "sed_max_pattern_length": int,
    "sed_max_replacement_length": int,
    "sed_max_input_length": int,
    "sed_max_output_length": int,
    "sed_cache_size": int,
    "poll_max_options": int,
    "poll_max_question_len": int,
    "poll_max_option_len": int,
    "poll_max_history_per_room": int,
    "poll_default_multi_max_choices": int,
    "pin_page_size": int,
    "pin_recent_cache_size": int,
    "karma_delay_seconds": int,
    "tell_delivery_delay_seconds": int,
    "xkcd_check_interval": int,
    "xkcd_index_start_delay_seconds": int,
    "xkcd_index_request_delay_seconds": (int, float),
    "xkcd_http_timeout": (int, float),
    "youtube_api_key": str,
    "reminder_enabled": bool,
    "reminder_max_age_days": int,
    "reminder_default_timezone": str,
    "version_check_enabled": bool,
    "version_check_interval": int,
    "version_check_url": str,
    "version_check_notify_jid": str,
    "room_invites_enabled": bool,
    "room_invite_notify_jid": str,
    "room_invite_max_age_days": int,
    "room_plugin_defaults": dict,
    "ducks": dict,
    "idlerpg": dict,
    "users": dict,
}


PYTHON_CONFIG_KEY_MAP = {
    "JID": "jid",
    "PASSWORD": "password",
    "NICK": "nick",
    "RESOURCE": "resource",
    "OWNER": "owner",
    "ADMINS": "admins",
    "COMMAND_PREFIX": "prefix",
    "LOG_LEVEL": "loglevel",
    "DB_FILE": "db",
    "RESTART_NOTIFICATION_FILE": "restart_notification_file",
    "COMMAND_TIMEOUT_SECONDS": "command_timeout_seconds",
    "COMMAND_SLOW_LOG_SECONDS": "command_slow_log_seconds",
    "DATABASE_BUSY_TIMEOUT_MS": "database_busy_timeout_ms",
    "DATABASE_WAL_ENABLED": "database_wal_enabled",
    "BACKUP_DIR": "backup_dir",
    "BACKUP_KEEP": "backup_keep",
    "BACKUP_RETENTION_DAYS": "backup_retention_days",
    "BACKUP_ON_START": "backup_on_start",
    "COMMAND_RATE_LIMIT_ENABLED": "command_rate_limit_enabled",
    "COMMAND_RATE_LIMIT_CAPACITY": "command_rate_limit_capacity",
    "COMMAND_RATE_LIMIT_REFILL_AMOUNT": "command_rate_limit_refill_amount",
    "COMMAND_RATE_LIMIT_REFILL_INTERVAL_SECONDS": "command_rate_limit_refill_interval_seconds",
    "COMMAND_RATE_LIMIT_DENY_WINDOW_SECONDS": "command_rate_limit_deny_window_seconds",
    "COMMAND_RATE_LIMIT_DENY_THRESHOLD": "command_rate_limit_deny_threshold",
    "COMMAND_RATE_LIMIT_BASE_BLOCK_SECONDS": "command_rate_limit_base_block_seconds",
    "COMMAND_RATE_LIMIT_BACKOFF_MULTIPLIER": "command_rate_limit_backoff_multiplier",
    "COMMAND_RATE_LIMIT_MAX_BLOCK_SECONDS": "command_rate_limit_max_block_seconds",
    "COMMAND_RATE_LIMIT_NOTIFY_COOLDOWN_SECONDS": "command_rate_limit_notify_cooldown_seconds",
    "COMMAND_RATE_LIMIT_BYPASS_ROLE": "command_rate_limit_bypass_role",
    "STOP_CMD": "stop_cmd",
    "AVATAR_PATH": "avatar",
    "AVATAR_TYPE": "avatar_type",
    "TIMEZONE": "timezone",
    "CONNECT_HOST": "host",
    "CONNECT_PORT": "port",
    "CONNECT_DIRECT_TLS": "direct_tls",
    "HTTP_TIMEOUT_SECONDS": "http_timeout_seconds",
    "HTTP_USER_AGENT": "http_user_agent",
    "ALLOW_PRIVATE_FETCH_URLS": "allow_private_fetch_urls",
    "XMPP_QUERY_TIMEOUT_SECONDS": "xmpp_query_timeout_seconds",
    "VCARD_FETCH_TIMEOUT_SECONDS": "vcard_fetch_timeout_seconds",
    "UPDATECHECK_TIMEOUT_SECONDS": "updatecheck_timeout_seconds",
    "YOUTUBE_API_KEY": "youtube_api_key",
    "REMINDER_ENABLED": "reminder_enabled",
    "REMINDER_MAX_AGE_DAYS": "reminder_max_age_days",
    "REMINDER_DEFAULT_TIMEZONE": "reminder_default_timezone",
    "RSS_GLOBAL_QUERY_INTERVAL": "rss_global_query_interval",
    "MAX_NEW_FEED_ENTRIES": "max_new_feed_entries",
    "RSS_MAX_ENTRIES_PER_POLL": "rss_max_entries_per_poll",
    "RSS_RETRY_INITIAL_DELAY": "rss_retry_initial_delay",
    "RSS_RETRY_BACKOFF_MULTIPLIER": "rss_retry_backoff_multiplier",
    "RSS_MAX_BACKOFF_TIME": "rss_max_backoff_time",
    "RSS_BROKEN_ERROR_THRESHOLD": "rss_broken_error_threshold",
    "RSS_SIMILARITY_THRESHOLD": "rss_similarity_threshold",
    "RSS_USER_AGENT": "rss_user_agent",
    "RSS_FETCH_TIMEOUT_SECONDS": "rss_fetch_timeout_seconds",
    "RSS_MAX_REDIRECTS": "rss_max_redirects",
    "RSS_MAX_READ_BYTES": "rss_max_read_bytes",
    "RSS_TEMPLATE_MAX_LENGTH": "rss_template_max_length",
    "URLCHECK_WAIT_SECONDS": "urlcheck_wait_seconds",
    "URLCHECK_FETCH_TIMEOUT_SECONDS": "urlcheck_fetch_timeout_seconds",
    "URLCHECK_MAX_REDIRECTS": "urlcheck_max_redirects",
    "URLCHECK_MAX_READ_BYTES": "urlcheck_max_read_bytes",
    "URLCHECK_USER_AGENT": "urlcheck_user_agent",
    "BIRTHDAY_CACHE_TTL_SECONDS": "birthday_cache_ttl_seconds",
    "BIRTHDAY_INITIAL_SCAN_DELAY_SECONDS": "birthday_initial_scan_delay_seconds",
    "BIRTHDAY_CHECK_INTERVAL_SECONDS": "birthday_check_interval_seconds",
    "SED_REGEX_TIMEOUT": "sed_regex_timeout",
    "SED_MAX_PATTERN_LENGTH": "sed_max_pattern_length",
    "SED_MAX_REPLACEMENT_LENGTH": "sed_max_replacement_length",
    "SED_MAX_INPUT_LENGTH": "sed_max_input_length",
    "SED_MAX_OUTPUT_LENGTH": "sed_max_output_length",
    "SED_CACHE_SIZE": "sed_cache_size",
    "POLL_MAX_OPTIONS": "poll_max_options",
    "POLL_MAX_QUESTION_LEN": "poll_max_question_len",
    "POLL_MAX_OPTION_LEN": "poll_max_option_len",
    "POLL_MAX_HISTORY_PER_ROOM": "poll_max_history_per_room",
    "POLL_DEFAULT_MULTI_MAX_CHOICES": "poll_default_multi_max_choices",
    "PIN_PAGE_SIZE": "pin_page_size",
    "PIN_RECENT_CACHE_SIZE": "pin_recent_cache_size",
    "KARMA_DELAY_SECONDS": "karma_delay_seconds",
    "TELL_DELIVERY_DELAY_SECONDS": "tell_delivery_delay_seconds",
    "XKCD_CHECK_INTERVAL": "xkcd_check_interval",
    "XKCD_INDEX_START_DELAY_SECONDS": "xkcd_index_start_delay_seconds",
    "XKCD_INDEX_REQUEST_DELAY_SECONDS": "xkcd_index_request_delay_seconds",
    "XKCD_HTTP_TIMEOUT": "xkcd_http_timeout",
    "VERSION_CHECK_ENABLED": "version_check_enabled",
    "VERSION_CHECK_INTERVAL": "version_check_interval",
    "VERSION_CHECK_URL": "version_check_url",
    "VERSION_CHECK_NOTIFY_JID": "version_check_notify_jid",
    "ROOM_INVITES_ENABLED": "room_invites_enabled",
    "ROOM_INVITE_NOTIFY_JID": "room_invite_notify_jid",
    "ROOM_INVITE_MAX_AGE_DAYS": "room_invite_max_age_days",
    "ROOM_PLUGIN_DEFAULTS": "room_plugin_defaults",
    "DUCKS": "ducks",
    "IDLERPG": "idlerpg",
    "USERS": "users",
}


NORMALIZED_CONFIG_KEYS = (
    set(DEFAULT_CONFIG)
    | set(REQUIRED_CONFIG_KEYS)
    | set(OPTIONAL_CONFIG_TYPES)
    | set(PYTHON_CONFIG_KEY_MAP.values())
)


CONFIG_DISPLAY_SECTIONS = (
    (
        "XMPP Account",
        ("JID", "PASSWORD", "NICK", "RESOURCE", "OWNER", "ADMINS"),
    ),
    (
        "Connection",
        (
            "CONNECT_HOST",
            "CONNECT_PORT",
            "CONNECT_DIRECT_TLS",
            "XMPP_QUERY_TIMEOUT_SECONDS",
        ),
    ),
    (
        "Bot Runtime",
        (
            "LOG_LEVEL",
            "COMMAND_PREFIX",
            "TIMEZONE",
            "DB_FILE",
            "RESTART_NOTIFICATION_FILE",
            "STOP_CMD",
            "COMMAND_TIMEOUT_SECONDS",
            "COMMAND_SLOW_LOG_SECONDS",
            "DATABASE_BUSY_TIMEOUT_MS",
            "DATABASE_WAL_ENABLED",
        ),
    ),
    (
        "Backups",
        (
            "BACKUP_DIR",
            "BACKUP_KEEP",
            "BACKUP_RETENTION_DAYS",
            "BACKUP_ON_START",
        ),
    ),
    (
        "Command Rate Limits",
        (
            "COMMAND_RATE_LIMIT_ENABLED",
            "COMMAND_RATE_LIMIT_CAPACITY",
            "COMMAND_RATE_LIMIT_REFILL_AMOUNT",
            "COMMAND_RATE_LIMIT_REFILL_INTERVAL_SECONDS",
            "COMMAND_RATE_LIMIT_DENY_WINDOW_SECONDS",
            "COMMAND_RATE_LIMIT_DENY_THRESHOLD",
            "COMMAND_RATE_LIMIT_BASE_BLOCK_SECONDS",
            "COMMAND_RATE_LIMIT_BACKOFF_MULTIPLIER",
            "COMMAND_RATE_LIMIT_MAX_BLOCK_SECONDS",
            "COMMAND_RATE_LIMIT_NOTIFY_COOLDOWN_SECONDS",
            "COMMAND_RATE_LIMIT_BYPASS_ROLE",
        ),
    ),
    (
        "HTTP Defaults",
        ("HTTP_TIMEOUT_SECONDS", "HTTP_USER_AGENT", "ALLOW_PRIVATE_FETCH_URLS"),
    ),
    (
        "vCard / Avatar",
        ("AVATAR_PATH", "AVATAR_TYPE", "VCARD_FETCH_TIMEOUT_SECONDS"),
    ),
    (
        "Release Update Check",
        (
            "VERSION_CHECK_ENABLED",
            "VERSION_CHECK_INTERVAL",
            "VERSION_CHECK_URL",
            "VERSION_CHECK_NOTIFY_JID",
            "UPDATECHECK_TIMEOUT_SECONDS",
        ),
    ),
    (
        "Room Invites",
        (
            "ROOM_INVITES_ENABLED",
            "ROOM_INVITE_NOTIFY_JID",
            "ROOM_INVITE_MAX_AGE_DAYS",
        ),
    ),
    (
        "Room Plugin Defaults",
        ("ROOM_PLUGIN_DEFAULTS",),
    ),
    (
        "URL Check",
        (
            "URLCHECK_WAIT_SECONDS",
            "URLCHECK_FETCH_TIMEOUT_SECONDS",
            "URLCHECK_MAX_REDIRECTS",
            "URLCHECK_MAX_READ_BYTES",
            "URLCHECK_USER_AGENT",
            "YOUTUBE_API_KEY",
        ),
    ),
    (
        "RSS / Atom",
        (
            "RSS_GLOBAL_QUERY_INTERVAL",
            "MAX_NEW_FEED_ENTRIES",
            "RSS_RETRY_INITIAL_DELAY",
            "RSS_RETRY_BACKOFF_MULTIPLIER",
            "RSS_MAX_BACKOFF_TIME",
            "RSS_BROKEN_ERROR_THRESHOLD",
            "RSS_SIMILARITY_THRESHOLD",
            "RSS_USER_AGENT",
            "RSS_FETCH_TIMEOUT_SECONDS",
            "RSS_MAX_REDIRECTS",
            "RSS_MAX_READ_BYTES",
            "RSS_TEMPLATE_MAX_LENGTH",
        ),
    ),
    (
        "Birthday Notify",
        (
            "BIRTHDAY_CACHE_TTL_SECONDS",
            "BIRTHDAY_INITIAL_SCAN_DELAY_SECONDS",
            "BIRTHDAY_CHECK_INTERVAL_SECONDS",
        ),
    ),
    (
        "Reminders",
        ("REMINDER_ENABLED", "REMINDER_MAX_AGE_DAYS"),
    ),
    (
        "Duck Game",
        ("DUCKS",),
    ),
    (
        "User Tracking",
        ("USERS",),
    ),
    (
        "Sed Corrections",
        (
            "SED_REGEX_TIMEOUT",
            "SED_MAX_PATTERN_LENGTH",
            "SED_MAX_REPLACEMENT_LENGTH",
            "SED_MAX_INPUT_LENGTH",
            "SED_MAX_OUTPUT_LENGTH",
            "SED_CACHE_SIZE",
        ),
    ),
    (
        "Polls",
        (
            "POLL_MAX_OPTIONS",
            "POLL_MAX_QUESTION_LEN",
            "POLL_MAX_OPTION_LEN",
            "POLL_MAX_HISTORY_PER_ROOM",
            "POLL_DEFAULT_MULTI_MAX_CHOICES",
        ),
    ),
    (
        "Pins",
        ("PIN_PAGE_SIZE", "PIN_RECENT_CACHE_SIZE"),
    ),
    (
        "Karma / Tell",
        ("KARMA_DELAY_SECONDS", "TELL_DELIVERY_DELAY_SECONDS"),
    ),
    (
        "XKCD",
        (
            "XKCD_CHECK_INTERVAL",
            "XKCD_INDEX_START_DELAY_SECONDS",
            "XKCD_INDEX_REQUEST_DELAY_SECONDS",
            "XKCD_HTTP_TIMEOUT",
        ),
    ),
)


_LOWER_TO_PYTHON_CONFIG_KEY = {
    normalized_key: python_key
    for python_key, normalized_key in PYTHON_CONFIG_KEY_MAP.items()
}

__all__ = [
    'BASE_DIR',
    'CONFIG_FILENAME',
    'LEGACY_CONFIG_FILENAME',
    'DEFAULT_CONFIG',
    'REQUIRED_CONFIG_KEYS',
    'OPTIONAL_CONFIG_TYPES',
    'PYTHON_CONFIG_KEY_MAP',
    'NORMALIZED_CONFIG_KEYS',
    'CONFIG_DISPLAY_SECTIONS',
    '_LOWER_TO_PYTHON_CONFIG_KEY',
]
