---
kind: pipeline
type: docker
name: pytest-3.12

steps:
- name: quality-and-test
  image: python:3.12
  commands:
    - python -m pip install -c constraints/python312.txt -r requirements.txt -r requirements-dev.txt
    - python -m pip check
    - python scripts/check_constraints.py constraints/python312.txt
    - sh scripts/quality.sh
    - python -m build
    - python scripts/check_wheel.py
    - pytest -W error::RuntimeWarning -W error::DeprecationWarning

trigger:
  event:
    - push
    - pull_request
    - tag

---
kind: pipeline
type: docker
name: pytest-3.13

steps:
- name: quality-and-test
  image: python:3.13
  commands:
    - python -m pip install -c constraints/python313.txt -r requirements.txt -r requirements-dev.txt
    - python -m pip check
    - python scripts/check_constraints.py constraints/python313.txt
    - sh scripts/quality.sh
    - python -m build
    - python scripts/check_wheel.py
    - pytest -W error::RuntimeWarning -W error::DeprecationWarning

trigger:
  event:
    - push
    - pull_request
    - tag
