---
kind: pipeline
type: docker
name: pytest-3.12

steps:
- name: quality-and-test
  image: python:3.12
  commands:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - python -m pip check
    - ./scripts/quality.sh
    - python -m build
    - pytest -W error::RuntimeWarning -W error::DeprecationWarning

trigger:
  event:
    - push
    - pull_request
    - tag

---
kind: pipeline
type: docker
name: pytest-3.13

steps:
- name: quality-and-test
  image: python:3.13
  commands:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - python -m pip check
    - ./scripts/quality.sh
    - python -m build
    - pytest -W error::RuntimeWarning -W error::DeprecationWarning

trigger:
  event:
    - push
    - pull_request
    - tag
