#!/bin/sh
set -eu

usage() {
    echo "usage: $0 <3.12|3.13>" >&2
    exit 2
}

version=${1:-}
case "$version" in
    3.12) interpreter=${PYTHON312:-python3.12}; output=constraints/python312.txt ;;
    3.13) interpreter=${PYTHON313:-python3.13}; output=constraints/python313.txt ;;
    *) usage ;;
esac

command -v "$interpreter" >/dev/null 2>&1 || {
    echo "interpreter not found: $interpreter" >&2
    exit 1
}

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT INT TERM
"$interpreter" -m venv "$tmp/venv"
"$tmp/venv/bin/python" -m pip install -c "$output" -r requirements.txt -r requirements-dev.txt
{
    echo "# Fully resolved dependency snapshot for Python $version."
    echo "# Generated by scripts/update-constraints.sh $version."
    "$tmp/venv/bin/python" -m pip freeze --all \
        | grep -v '^pip==' \
        | grep -v '^setuptools==' \
        | grep -v '^wheel==' \
        | sort -f
} > "$output"
echo "updated $output"
